#!/usr/bin/env tsx
/**
 * Sync CMS → static, uruchamiany w `prebuild` (przed `next build`).
 *
 * 1. Czyta CMS z DataStore (gdy zarejestrowany) albo Medusa Store.metadata.
 * 2. Ściąga zdalne obrazy CMS do `public/images/cms/`.
 * 3. Generuje `src/static-cms-media-map.ts` w pakiecie cms lub w aplikacji docelowej.
 *
 * Brak credentials / błąd = no-op (build trwa, runtime spada na dynamiczny fetch + defaults).
 */

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { Readable } from "node:stream";
import { normalizeCmsImageToWebp } from "@moduly/magazyn-core/storage/normalize-cms-image";
import {
	assembleMetadataBlobFromDataStore,
	fetchMedusaMetadataBlob,
	getDataStore,
	MEDUSA_METADATA_KEYS,
	type RawStoreMetadataBlob,
} from "@moduly/data-store";
import {
	MAGAZYN_GLOBAL_CONTENT_KEY,
	MAGAZYN_PAGE_CONTENT_KEY,
	MAGAZYN_PAGE_SEO_KEY,
	MAGAZYN_SITE_SETTINGS_KEY,
} from "../src/metadata-keys";

const CMS_PACKAGE_ROOT = path.resolve(import.meta.dirname, "..");
const APP_ROOT = process.env.MODULY_APP_ROOT?.trim() || process.cwd();
const PUBLIC_DIR = path.join(APP_ROOT, "public");
const CMS_IMAGES_DIR = path.join(PUBLIC_DIR, "images", "cms");
const STATIC_MEDIA_MAP_FILE =
	process.env.MODULY_CMS_MEDIA_MAP_FILE?.trim() ||
	path.join(CMS_PACKAGE_ROOT, "src", "static-cms-media-map.ts");

function parseMaybeJson(value: unknown): unknown {
	if (typeof value !== "string") return value;
	try {
		return JSON.parse(value);
	} catch {
		return value;
	}
}

function blobToSyncRecord(blob: RawStoreMetadataBlob): Record<string, unknown> {
	return {
		[MAGAZYN_SITE_SETTINGS_KEY]: parseMaybeJson(blob.siteSettings),
		[MAGAZYN_PAGE_SEO_KEY]: parseMaybeJson(blob.pageSeo),
		[MAGAZYN_PAGE_CONTENT_KEY]: parseMaybeJson(blob.pageContent),
		[MAGAZYN_GLOBAL_CONTENT_KEY]: parseMaybeJson(blob.globalContent),
	};
}

async function loadCmsBlob(): Promise<Record<string, unknown> | null> {
	const dataStore = getDataStore();
	if (dataStore) {
		const pageIds =
			process.env.MODULY_CMS_PAGE_IDS?.split(",")
				.map((id) => id.trim())
				.filter(Boolean) ?? ["home", "shop"];
		const blob = await assembleMetadataBlobFromDataStore(dataStore, pageIds);
		return blobToSyncRecord(blob);
	}

	const blob = await fetchMedusaMetadataBlob();
	if (!blob) return null;

	const parsed: Record<string, unknown> = {};
	for (const key of MEDUSA_METADATA_KEYS) {
		const field =
			key === MAGAZYN_SITE_SETTINGS_KEY
				? blob.siteSettings
				: key === MAGAZYN_PAGE_SEO_KEY
					? blob.pageSeo
					: key === MAGAZYN_PAGE_CONTENT_KEY
						? blob.pageContent
						: blob.globalContent;
		if (field !== undefined) parsed[key] = parseMaybeJson(field);
	}
	return parsed;
}

const IMAGE_EXT = /\.(jpe?g|png|webp|gif|avif)$/i;

function isRemoteImageUrl(value: string): boolean {
	return /^https?:\/\//i.test(value) && IMAGE_EXT.test(value.split("?")[0] ?? "");
}

function collectRemoteImageUrls(node: unknown, acc: Set<string>): void {
	if (typeof node === "string") {
		if (isRemoteImageUrl(node)) acc.add(node);
	} else if (Array.isArray(node)) {
		for (const item of node) collectRemoteImageUrls(item, acc);
	} else if (node && typeof node === "object") {
		for (const val of Object.values(node)) collectRemoteImageUrls(val, acc);
	}
}

function localFilenameFor(url: string): string {
	const hash = crypto.createHash("sha1").update(url).digest("hex").slice(0, 8);
	let base = "asset";
	try {
		base = path.basename(new URL(url).pathname).replace(/\.[^.]+$/, "") || "asset";
	} catch {
		/* keep default */
	}
	return `${hash}-${base}.webp`;
}

async function downloadImage(url: string, filename: string): Promise<boolean> {
	const res = await fetch(url, { signal: AbortSignal.timeout(30_000) });
	if (!res.ok || !res.body) {
		console.warn(`    ⚠ pominięto (HTTP ${res.status}): ${url}`);
		return false;
	}

	const chunks: Buffer[] = [];
	for await (const chunk of Readable.fromWeb(res.body as never)) {
		chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
	}

	const webp = await normalizeCmsImageToWebp(Buffer.concat(chunks));
	const filepath = path.join(CMS_IMAGES_DIR, filename);
	fs.writeFileSync(filepath, webp);
	return true;
}

async function downloadAllImages(parsed: Record<string, unknown>): Promise<Map<string, string>> {
	const urls = new Set<string>();
	collectRemoteImageUrls(parsed, urls);

	console.log(`\n📦 Znaleziono ${urls.size} zdalnych obrazów CMS`);
	fs.mkdirSync(CMS_IMAGES_DIR, { recursive: true });

	const urlMap = new Map<string, string>();
	for (const url of urls) {
		const filename = localFilenameFor(url);
		console.log(`  → ${filename}`);
		const ok = await downloadImage(url, filename);
		if (ok) urlMap.set(url, `/images/cms/${filename}`);
	}
	return urlMap;
}

function generateMediaMapFile(urlMap: Map<string, string>): void {
	const record = Object.fromEntries(urlMap.entries());
	const content = `// Auto-generated by scripts/sync-cms-to-static.ts
// Mapuje zdalne URL-e obrazów CMS → lokalne \`/images/cms/…\` (hybrid: tekst live, media po prebuild).

export const STATIC_CMS_MEDIA_URL_MAP: Record<string, string> = ${JSON.stringify(record, null, 2)};
`;
	fs.mkdirSync(path.dirname(STATIC_MEDIA_MAP_FILE), { recursive: true });
	fs.writeFileSync(STATIC_MEDIA_MAP_FILE, content, "utf-8");
	console.log(
		`\n✓ Zapisano ${path.relative(APP_ROOT, STATIC_MEDIA_MAP_FILE)} (${urlMap.size} mapowań)`,
	);
}

async function main() {
	console.log("🚀 Sync CMS → static...\n");

	try {
		const parsed = await loadCmsBlob();
		if (!parsed) {
			console.log("⚠ Sync pominięty — brak danych CMS (DataStore / Medusa).\n");
			process.exit(0);
		}

		const urlMap = await downloadAllImages(parsed);
		generateMediaMapFile(urlMap);

		console.log(
			`\n✨ Sync zakończony — ${urlMap.size} obrazów zlokalizowanych (tekst CMS = live).\n`,
		);
	} catch (error) {
		console.error("\n❌ Sync nieudany:", error);
		console.error("⚠ Build kontynuuje — runtime spadnie na dynamiczny fetch.\n");
		process.exit(0);
	}
}

main();
